site_name: CSA_Wiki
site_description: 驯海隔壁白帽子
site_author: 中国民航大学网络安全协会
site_url: https://cauc-csa.github.io/
copyright: Copyright &copy; 2023 - 2025 中国民航大学网络安全协会

repo_name: CAUC-CSA/CAUC-CSA.github.io
repo_url: https://github.com/CAUC-CSA/CAUC-CSA.github.io
edit_uri: edit/master/docs/

extra_javascript:
  - https://cdn.jsdelivr.net/npm/pangu@4.0.7/dist/browser/pangu.js
  - assets/javascripts/pangu-init.js

theme:
  name: material
  language: zh
  logo: images/csa_logo.png
  favicon: images/csa_logo.png
  
  features:
    - content.code.annotate           # 代码注释
    - content.code.copy               # 代码块复制按钮
    - navigation.footer               # 页脚上下页导航
    - navigation.instant              # 即时加载
    - navigation.instant.progress     # 加载进度条
    - navigation.tabs                 # 导航栏标签页
    - navigation.tabs.sticky          # 粘性标签页
    - navigation.top                  # 返回顶部按钮
    - navigation.tracking             # 锚点跟踪
    - search.highlight                # 搜索高亮
    - search.share                    # 搜索分享
    - search.suggest                  # 搜索建议
    - toc.follow                      # 目录跟随

  # 配色方案
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # 图标配置
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

# Markdown 扩展
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 6
  
  # PyMdown Extensions
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
      linenums: true
  - pymdownx.blocks.caption
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

# 插件配置
plugins:
  - search:
      separator: '[\s\u200b\-]'
      lang:
        - zh
        - en
  - include-markdown
  # 文档地址：https://jaywhj.netlify.app/document-dates-zh
  - document-dates:
      position: bottom          # 显示位置: top(标题后) bottom(文档末尾)
      type: datetime            # 时间类型: date datetime timeago, 默认：date
      exclude:                  # 排除文件列表
      date_format: '%Y-%m-%d'   # 日期格式化字符串（例如：%Y年%m月%d日、%b %d, %Y）
      time_format: '%H:%M:%S'   # 时间格式化字符串（仅在 type=datetime 时有效）
      show_author: false        # 作者显示模式: true(头像) text(文本) false(隐藏)

# 导航栏配置
nav:
  - 首页: index.md
  - 培训资料&&教程集合:
      - CTF是什么: training/what-is-ctf.md
      - 环境与工具准备: 
        - 01_VMWare虚拟机的安装: training/tools/vmware/index.md
        - 02_Docker超绝入门指南: training/tools/docker/docker.md
        - 03_Python安装与基础配置: training/tools/python/python.md
      - 靶场推荐: training/lab.md
  - CTF技能树:
      - Introduction: ctf/ctf_index.md
      - Web: 
        - Introduction: ctf/web/web.md
        - Web中你需要知道的计网知识: ctf/web/network_in_web/Web中你需要知道的计网知识.md
      - Crypto:
        - xxx: ctf/crypto/crypto.md
      - Pwn:
        - xxx: ctf/pwn/pwn.md
      - Reverse:
        - xxx: ctf/reverse/reverse.md
      - Misc:
        - xxx: ctf/misc/misc.md
  - Wiki建设:
      - 提交规范: contributing/contributing.md
      - 撰写规范: contributing/writing.md
